const Constants = {
  mutation: {
    UPDATE_SEARCH_PAYLOAD: 'UPDATE_SEARCH_PAYLOAD',
    UPDATE_DOC_LIST_SUCCESS: 'UPDATE_DOC_LIST_SUCCESS',
    UPDATE_DOC_LIST_START: 'UPDATE_DOC_LIST_START',
    UPDATE_DOC_LIST_FAILED: 'UPDATE_DOC_LIST_FAILED',
    RESET_SEARCH_FIELD: 'RESET_SEARCH_FIELD',
    TOGGLE_SEARCHING_FLAG: 'TOGGLE_SEARCHING_FLAG',
    CHANGE_PAGE_NUMBER: 'CHANGE_PAGE_NUMBER'
  },
  action: {
    GET_DOC_LIST: 'GET_DOC_LIST',
  }
};
export default Constants;
