const Constants = {
  mutation: {
    UPDATE_SEARCH_PAYLOAD: 'UPDATE_SEARCH_PAYLOAD',
    UPDATE_DOC_LIST_SUCCESS: 'UPDATE_DOC_LIST_SUCCESS',
    UPDATE_DOC_LIST_START: 'UPDATE_DOC_LIST_START',
    UPDATE_DOC_LIST_FAILED: 'UPDATE_DOC_LIST_FAILED',
    RESET_SEARCH_FIELD: 'RESET_SEARCH_FIELD',
    TOGGLE_SEARCHING_FLAG: 'TOGGLE_SEARCHING_FLAG',
    CHANGE_PAGE_NUMBER: 'CHANGE_PAGE_NUMBER',
    SERVICE_ERROR_OCCURED: 'SERVICE_ERROR_OCCURED',
    SERVICE_ERROR_RESET: 'SERVICE_ERROR_RESET',
    DELETE_SEARCH_ITEM_VALUE: 'DELETE_SEARCH_ITEM_VALUE'
  },
  action: {
    GET_DOC_LIST: 'GET_DOC_LIST',
    SERVICE_ERROR_OCCURED: 'SERVICE_ERROR_OCCURED',
  }
};
export default Constants;
